### ISSUE TITLE
Archives page

### ISSUE THREAD

**Issue by icarnaghan** [mikejolley/wp-post-series#24]
Is there a plan to add an archives page, e.g. mysite.com/series/series-name?

**Comment by mikejolley** [comment]
You can enable archive support by toggling this filter with custom code:

https://github.com/mikejolley/wp-post-series/blob/master/src/TaxonomyController.php#L69

```
add_filter( 'wp_post_series_enable_archive', '__return_true' );
```

It is disabled by default because enabling archives would lead to template/theme conflicts. You may need to do some extra theme styling/templating to make that archive look good.
